import { useSmoothScroll } from '@/motion/scroll';
import { Nav } from '@/components/common/Nav';
import { Footer } from '@/components/common/Footer';
import { Cursor } from '@/components/common/Cursor';
import { insights } from '@/content/data';
import { useParams, Link } from 'wouter';
import NotFound from '@/pages/not-found';

export function InsightDetail() {
  useSmoothScroll();
  const params = useParams();
  const insight = insights.find(i => i.slug === params.slug);

  if (!insight) return <NotFound />;

  return (
    <div className="bg-bg-0 min-h-screen text-text-main">
      <Cursor />
      <Nav />

      <main className="pt-48 pb-32 max-w-3xl mx-auto px-6">
        <article>
          <header className="mb-16">
            <Link href="/insights" className="text-sm font-mono uppercase tracking-wider text-text-2 hover:text-text-main mb-12 inline-block">← All Insights</Link>
            <span className="text-eyebrow text-accent mb-6 block">{insight.date}</span>
            <h1 className="text-5xl md:text-6xl font-display font-bold leading-tight mb-8">{insight.title}</h1>
            <p className="text-2xl text-text-2 leading-relaxed">{insight.excerpt}</p>
          </header>

          <div className="prose prose-invert prose-lg max-w-none text-text-main prose-headings:font-display prose-headings:text-text-main prose-a:text-accent">
            <p>{insight.content}</p>
            {/* Adding mock content for length to show typography */}
            <h2>The core of the issue</h2>
            <p>Most development teams treat the frontend as a necessary evil to display backend data. We treat it as the product itself. When you optimize for the developer experience over the user experience, you end up with generic interfaces that fail to capture imagination.</p>
            <p>Every micro-interaction should feel intentional. Every animation should be driven by a physical equation. If an element enters the screen, it shouldn't just appear—it should arrive.</p>
            <blockquote>
              <p>The difference between a good website and a memorable one is often invisible to the eye, but entirely perceptible to the mind.</p>
            </blockquote>
            <h2>Looking forward</h2>
            <p>As the barrier to entry drops for basic web development, the premium for extreme craft rises exponentially. Templates will eat the bottom 80% of the market. The top 20% will demand bespoke, immersive experiences that cannot be generated by a prompt alone.</p>
          </div>
        </article>
      </main>
      <Footer />
    </div>
  );
}
